// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI } from '../runtime';
import {
    HeaderByteRange,
} from '../models';

export interface FilesGetContentsRequest {
    systemId: string;
    path: string;
    range?: HeaderByteRange;
    more?: number;
}

/**
 * no description
 */
export class ContentApi extends BaseAPI {

    /**
     * Get file contents/serve file
     * Retrieve a file from the files service
     */
    filesGetContents = ({ systemId, path, range, more }: FilesGetContentsRequest): Observable<void> => {
        throwIfNullOrUndefined(systemId, 'filesGetContents');
        throwIfNullOrUndefined(path, 'filesGetContents');

        const headers: HttpHeaders = {
            ...(range != null ? { 'range': String(range) } : undefined),
            ...(more != null ? { 'more': String(more) } : undefined),
        };

        return this.request<void>({
            path: '/v3/files/content/{systemId}/{path}'.replace('{systemId}', encodeURI(systemId)).replace('{path}', encodeURI(path)),
            method: 'GET',
            headers,
        });
    };

}
