// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI } from '../runtime';
import {
    HealthCheckResponse,
} from '../models';

/**
 * no description
 */
export class HealthApi extends BaseAPI {

    /**
     * Health check
     * Health check
     */
    healthCheck = (): Observable<HealthCheckResponse> => {
        return this.request<HealthCheckResponse>({
            path: '/v3/files/healthcheck',
            method: 'GET',
        });
    };

}
