// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FileInfo
 */
export interface FileInfo {
    /**
     * @type {number}
     * @memberof FileInfo
     */
    lastModified?: number;
    /**
     * @type {string}
     * @memberof FileInfo
     */
    name?: string;
    /**
     * @type {string}
     * @memberof FileInfo
     */
    path?: string;
    /**
     * size in kB
     * @type {number}
     * @memberof FileInfo
     */
    size?: number;
}
