// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FilePermission,
} from './';

/**
 * @export
 * @interface FilePermissionResponse
 */
export interface FilePermissionResponse {
    /**
     * @type {string}
     * @memberof FilePermissionResponse
     */
    status?: string;
    /**
     * @type {string}
     * @memberof FilePermissionResponse
     */
    message?: string;
    /**
     * @type {FilePermission}
     * @memberof FilePermissionResponse
     */
    result?: FilePermission;
    /**
     * @type {string}
     * @memberof FilePermissionResponse
     */
    version?: string;
}
