// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FileInfo,
} from './';

/**
 * @export
 * @interface FileListingResponse
 */
export interface FileListingResponse {
    /**
     * @type {string}
     * @memberof FileListingResponse
     */
    status?: string;
    /**
     * @type {string}
     * @memberof FileListingResponse
     */
    message?: string;
    /**
     * @type {Array<FileInfo>}
     * @memberof FileListingResponse
     */
    result?: Array<FileInfo>;
    /**
     * @type {string}
     * @memberof FileListingResponse
     */
    version?: string;
}
