// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FormDataContentDisposition
 */
export interface FormDataContentDisposition {
    /**
     * @type {string}
     * @memberof FormDataContentDisposition
     */
    type?: string;
    /**
     * @type {{ [key: string]: string; }}
     * @memberof FormDataContentDisposition
     */
    parameters?: { [key: string]: string; };
    /**
     * @type {string}
     * @memberof FormDataContentDisposition
     */
    fileName?: string;
    /**
     * @type {string}
     * @memberof FormDataContentDisposition
     */
    creationDate?: string;
    /**
     * @type {string}
     * @memberof FormDataContentDisposition
     */
    modificationDate?: string;
    /**
     * @type {string}
     * @memberof FormDataContentDisposition
     */
    readDate?: string;
    /**
     * @type {number}
     * @memberof FormDataContentDisposition
     */
    size?: number;
    /**
     * @type {string}
     * @memberof FormDataContentDisposition
     */
    name?: string;
}
