// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface HeaderByteRange
 */
export interface HeaderByteRange {
    /**
     * @type {number}
     * @memberof HeaderByteRange
     */
    min?: number;
    /**
     * @type {number}
     * @memberof HeaderByteRange
     */
    max?: number;
}
