// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FormDataContentDisposition,
} from './';

/**
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * @type {FormDataContentDisposition}
     * @memberof InlineObject
     */
    file?: FormDataContentDisposition;
}
