// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SharedFileObject
 */
export interface SharedFileObject {
    /**
     * Username who shared the file/folder
     * @type {string}
     * @memberof SharedFileObject
     */
    creator?: string;
    /**
     * Username who was granted access
     * @type {string}
     * @memberof SharedFileObject
     */
    sharedWith?: string;
    /**
     * Creation timestamp in UTC
     * @type {string}
     * @memberof SharedFileObject
     */
    created?: string;
    /**
     * Number of seconds in which the share was set to expire.
     * @type {number}
     * @memberof SharedFileObject
     */
    expiresIn?: number;
    /**
     * Link to the shared file.
     * @type {string}
     * @memberof SharedFileObject
     */
    url?: string;
}
