// tslint:disable
/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TapisResponse
 */
export interface TapisResponse {
    /**
     * @type {string}
     * @memberof TapisResponse
     */
    status?: string;
    /**
     * @type {string}
     * @memberof TapisResponse
     */
    message?: string;
    /**
     * @type {object}
     * @memberof TapisResponse
     */
    result?: object;
    /**
     * @type {string}
     * @memberof TapisResponse
     */
    version?: string;
}
